---
book_repo: docs-book
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.8
  changelog_href: http://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
public_host: hello

sections:
  - repository:
      name: docs-content
    directory: windows
    subnav_template: windows_subnav.erb       

template_variables:                             # optional

book_title: Partner Services Template
book_repo: docs-book
layout_repo: docs-layout
